version: '3.7'

services:

  app_dev:
    image: golang:1.16.3-buster
    restart: always
    working_dir: /app
    ports:
      - "3001:3000"
    volumes:
      - ${PWD}:/app
      - /home/dev/go:/go:ro
    command: ["go", "run", "."]
    
  db:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: simple
      MONGO_INITDB_DATABASE: example
    volumes:
      - db:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

volumes:
  db: