// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/app.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SegmentServiceClient is the client API for SegmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SegmentServiceClient interface {
	StoreUserSegmentation(ctx context.Context, in *UserSegmentRequest, opts ...grpc.CallOption) (*UserSegmentResponse, error)
	ShowUserInSegment(ctx context.Context, in *SegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error)
	Estimate(ctx context.Context, in *SegmentRequest, opts ...grpc.CallOption) (*EstimateResponse, error)
}

type segmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSegmentServiceClient(cc grpc.ClientConnInterface) SegmentServiceClient {
	return &segmentServiceClient{cc}
}

func (c *segmentServiceClient) StoreUserSegmentation(ctx context.Context, in *UserSegmentRequest, opts ...grpc.CallOption) (*UserSegmentResponse, error) {
	out := new(UserSegmentResponse)
	err := c.cc.Invoke(ctx, "/proto.SegmentService/StoreUserSegmentation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) ShowUserInSegment(ctx context.Context, in *SegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error) {
	out := new(SegmentResponse)
	err := c.cc.Invoke(ctx, "/proto.SegmentService/ShowUserInSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *segmentServiceClient) Estimate(ctx context.Context, in *SegmentRequest, opts ...grpc.CallOption) (*EstimateResponse, error) {
	out := new(EstimateResponse)
	err := c.cc.Invoke(ctx, "/proto.SegmentService/Estimate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SegmentServiceServer is the server API for SegmentService service.
// All implementations must embed UnimplementedSegmentServiceServer
// for forward compatibility
type SegmentServiceServer interface {
	StoreUserSegmentation(context.Context, *UserSegmentRequest) (*UserSegmentResponse, error)
	ShowUserInSegment(context.Context, *SegmentRequest) (*SegmentResponse, error)
	Estimate(context.Context, *SegmentRequest) (*EstimateResponse, error)
	// mustEmbedUnimplementedSegmentServiceServer()
}

// UnimplementedSegmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSegmentServiceServer struct {
}

func (UnimplementedSegmentServiceServer) StoreUserSegmentation(context.Context, *UserSegmentRequest) (*UserSegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreUserSegmentation not implemented")
}
func (UnimplementedSegmentServiceServer) ShowUserInSegment(context.Context, *SegmentRequest) (*SegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowUserInSegment not implemented")
}
func (UnimplementedSegmentServiceServer) Estimate(context.Context, *SegmentRequest) (*EstimateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Estimate not implemented")
}
func (UnimplementedSegmentServiceServer) mustEmbedUnimplementedSegmentServiceServer() {}

// UnsafeSegmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SegmentServiceServer will
// result in compilation errors.
type UnsafeSegmentServiceServer interface {
	mustEmbedUnimplementedSegmentServiceServer()
}

func RegisterSegmentServiceServer(s grpc.ServiceRegistrar, srv SegmentServiceServer) {
	s.RegisterService(&SegmentService_ServiceDesc, srv)
}

func _SegmentService_StoreUserSegmentation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).StoreUserSegmentation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SegmentService/StoreUserSegmentation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).StoreUserSegmentation(ctx, req.(*UserSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_ShowUserInSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).ShowUserInSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SegmentService/ShowUserInSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).ShowUserInSegment(ctx, req.(*SegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SegmentService_Estimate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmentServiceServer).Estimate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SegmentService/Estimate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmentServiceServer).Estimate(ctx, req.(*SegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SegmentService_ServiceDesc is the grpc.ServiceDesc for SegmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SegmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SegmentService",
	HandlerType: (*SegmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreUserSegmentation",
			Handler:    _SegmentService_StoreUserSegmentation_Handler,
		},
		{
			MethodName: "ShowUserInSegment",
			Handler:    _SegmentService_ShowUserInSegment_Handler,
		},
		{
			MethodName: "Estimate",
			Handler:    _SegmentService_Estimate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/app.proto",
}
